package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test")) {
    dependencies {
        remove(AbsoluteId("MavenSample_SheepProject_FailingCountingTests")) {
            snapshot {
            }
        }

        add(AbsoluteId("CopyMavenSample_SheepProject_CountingTests")) {
            snapshot {
            }
        }

        add(RelativeId("Up")) {
            snapshot {
            }
        }

    }
}
